services:
  - type: web
    name: price-checker
    env: node
    rootDir: server
    buildCommand: |
      pwd
      cd ../app && npm install && npm run build
      pwd
      npm install
    startCommand: |
      pwd
      npm start
    envVars:
      - key: NODE_ENV
        value: production
